### ISSUE TITLE
Make it a clean Symfony bundle

### ISSUE THREAD

**Issue by leofeyer** [tenside/core#11]
```
src/
    Annotation/
    Command/
    Composer/
    Config/
    Console/
    Controller/
    DependencyInjection/
    EventListener/
    Events/
    Resources/
    Security/
    SelfTest/
    Task/
    Util/
    TensideCoreBundle.php
tests/
    …
```

I'd also change the following:

* Move `src/stub.php` into `src/Resource`
* Move everything but the `TensideCoreBundle` class from the bundle root into the `Util` namespace

**Comment by leofeyer** [comment]
I can also do the work for you, if you want. Just add me as maintainer.

**Comment by leofeyer** [comment]
We also need to adjust contao/package-manager once the changes have been merged.

**Comment by leofeyer** [comment]
As discussed, we want to split the code into a library and a bundle. @discordier will do this today.

**Comment by discordier** [comment]
See https://github.com/tenside/core-bundle

**Comment by leofeyer** [comment]
:+1:
