### ISSUE TITLE
API endpoint for composer version validation

### ISSUE THREAD

**Issue by Toflar** [tenside/core#12]
Can we have a general endpoint to validate a version entered by the user against the composer version formats? I think it's not the way to go to implement this in JS as it's all already available in PHP. So a `validation/version` or so would be great :)

**Comment by discordier** [comment]
You mean constraint validation I suppose?

**Comment by Toflar** [comment]
Yes, something like is '^2.0' valid or not :-)

**Comment by discordier** [comment]
Fixed in https://github.com/tenside/core-bundle/commit/1ea949db522147afacfc901b67fd21a5dba845ca
