### ISSUE TITLE
RepositoryInterface::findPackage

### ISSUE THREAD

**Issue by aschempp** [tenside/core#2]
Are you aware there's a method to find packages in the repository?

Just asking because of this:
https://github.com/tenside/core/blob/5c072888ea62b1c04caf75c2679b75fe12876654/src/CoreBundle/Controller/PackageController.php#L85

**Comment by discordier** [comment]
Yes, but if you check the implementation, it will simply perform the name check including a check for a constraint and if present, apply it. Therefore the implementation would be more expensive in this case (as it is always an ArrayRepository).
