### ISSUE TITLE
Invalid result check for Task::perform

### ISSUE THREAD

**Issue by aschempp** [tenside/core#3]
`Task::perform` does not return a result, but it's checked here:
https://github.com/tenside/core/blob/master/src/Task/Runner.php#L54

PS: why do we need the `Runner` at all?

**Comment by discordier** [comment]
It was intended as abstraction for the future "InlineRunner" which is independent of the `proc_open` availability but has been stripped down to an redundant class.

You are right about the return code however.

**Comment by aschempp** [comment]
Fixed in fbb74985c87770c396a68643e0d0a28b9d77d144
