### ISSUE TITLE
Use HTTP status codes

### ISSUE THREAD

**Issue by aschempp** [tenside/core#4]
I just noticed we're using a JSON `STATUS` variable. We should better use HTTP status codes.

Example:
https://github.com/tenside/core/blob/master/src/CoreBundle/Controller/AppKernelController.php#L62 should use 4xx and 2xx status codes.

**Comment by discordier** [comment]
I wonder if this would really be the best solutions as some browsers seemed to not return all error codes (I do not recall which ones at the moment).

The status codes that would be applicable would be:
- "400 Bad Request"
- "406 Not Acceptable"
- "412 Precondition Failed"
- "417 Expectation Failed"

**Comment by aschempp** [comment]
Same here:
https://github.com/tenside/core/blob/master/src/CoreBundle/Controller/TaskRunnerController.php#L124-L131

A successful task launch should be `201`, but no task found should certainly not be `status = OK`.

**Comment by discordier** [comment]
Unsure if running a detached process can be considered "201 Created" but yes, the other one should be 404 for sure.

**Comment by discordier** [comment]
Sending 201 did not work out, had to revert in b075de89cd5a753ff986d41993047b8bbc1546fc as chrome did wait for a final result status indefinitely.
See also HTTP RFC for 201 status code, we must send a final result when the processing has finished.
