### ISSUE TITLE
Unnecessary package ordering

### ISSUE THREAD

**Issue by aschempp** [tenside/core#5]
https://github.com/tenside/core/blob/master/src/Composer/PackageConverter.php#L164

I think this is unnecessary. The display order is a task for the UI. It would be better if the API returned the packages in the order they are defined in Composer, as that would probably be the "priority" or the "require" list?

**Comment by discordier** [comment]
Might be... we can remove it.

**Comment by discordier** [comment]
Packages do not get sorted anymore
