### ISSUE TITLE
Strange method TaskList::createTaskFromMetadata

### ISSUE THREAD

**Issue by aschempp** [tenside/core#6]
https://github.com/tenside/core/blob/master/src/Task/TaskList.php#L87

The event loop looks like something a factory should handle instead of an event listener?

**Comment by discordier** [comment]
Yep, dispatching the event is a "factory".
However it is intended for extendability and therefore I used events as this is code from pre-symfony-standard.
We could also change it to a factory with registration of task handlers but this is low prio atm.

**Comment by aschempp** [comment]
I agree, appart from the fact that only half the available tasks are handled ;-)

**Comment by discordier** [comment]
This portion has been completely rewritten as real factories.
