### ISSUE TITLE
Uncatched exception for task status

### ISSUE THREAD

**Issue by aschempp** [tenside/core#8]
https://github.com/tenside/core/blob/master/src/CoreBundle/Controller/TaskRunnerController.php#L75

The `Task::output()` method throws an exception if the task is not started. It should be catched or the method should not be called depending on the task status.

**Comment by discordier** [comment]
The exception is intended, however, we could add a new state "queued" and therefore have the missing link for the "get running task". This will however involve keeping the task in the list and therefore a rewrite of said list to not be a FIFO anymore.

**Comment by discordier** [comment]
The new state has been added and the exception removed.
